image: node:10

stages:
- build
- deploy

build:
  stage: build
  script:
    - npm install && npm rebuild node-sass && npm run build
    
deploy:
  stage: deploy
  before_script:
    - echo "deploying..."
  script:
    - curl $DEPLOY_URL/systems-offline/$CI_COMMIT_SHA
