image: node:10

stages:
- build
- deploy

build:
  stage: build
  script:
    - npm install && npm run build
    
deploy:
  stage: deploy
  before_script:
    - echo "deploying..."
  script:
    - curl http://deploy.zerophp.org/systems-offline/$CI_COMMIT_SHA
